#! /bin/sh

#bspc monitor -d I II III IV V VI VII VIII IX
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width 1
bspc config window_gap 8
bspc config focus_follows_pointer true

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config single_monocle true

feh --bg-center /usr/share/wallpaper/trees.jpg
